# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YCMjqHFdyM6P2VTct8louNlS7J9WsEis
"""

num=int(input("Enter number:"))
limit=int(input("Enter limit"))
print("Multiplication table")
for i in range(1,limit+1):
  mul=i*num
  print(str(i)+"x"+str(num)+"="+str(mul))

num=int(input("Enter limit:"))
first=0
second=1
print("\nFibonacci series:")
print(first)
print(second)
for i in range(2, num):
  next=first+second
  print(next)
  first=second 
  second=next

a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
if(a>b):
    max=a
else:
    max=b
while(1):
    if(max%a==0 and max%b==0):
        print("LCM is:",max)
        break
    max=max+1

num=int(input("Enter Number"))
count=0
while(num!=0):
  num=num//10
  count=count+1
print("Number of digits:%d"%count)

num=int(input("Enter number:"))
rev=0
while (num>0):
  rem=num%10
  rev=(rev*10)+rem
  num=num//10
print("Reverse of entered number:%d"%rev)

num=int(input("Enter Number:"))
pow=int(input("Enter power:"))
power=1
for i in range(1,pow+1):
  power=power*num
print("power of number:",power)

num=int(input("Enter Number:"))
reserve=num
reverse=0
while (num>0):
  remainder=num%10
  reverse=(reverse*10)+remainder
  num=num//10
if (reserve==reverse):
  print("Number is palindrome")
else:
  print("Number is not palindrome")