# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mANzaaYwmuVxSEXMoK8DkjKN3Dumz4Pi

"""

a=5
print("datatype of a is",type(a))
b=2.0
print("\nDatatype of a is:",type(b))
c=3+5j
print("\nDatatype of a is:",type(c))
print("the value of ",d," is of the type",type(d))
e={"ads","web","python"}
print("the value of ",e," is of the type",type(e))
f=("ads","web","python")
print("the value of ",f," is of the type",type(f))
g=["ads","web","python"]
print("the value of ",g," is of the type",type(g))
h=range(5)
print("the value of ",h," is of the type",type(h))
i=True
print("the value of ",i," is of the type",type(i))

print("Hello, World!")

num= int(input("Enter a number:"))
print("Enterd number is: "+str(num))

n1=int(input("Enter first number:"))
n2=int(input("Enter second number:"))
sum=n1+n2
print("sum:"+str(sum))

f=float(input("first number:"))
s=float(input("second number:"))
mul=s*f
print("Result:"+str(mul))

n1=int(input("Divident:"))
n2=int(input("Divisor:"))
q=n1//n2
r=n1%n2
print("Quotient:"+str(q))
print("Remainder:"+str(r))

a=int(input("Enter First Number:"))
b=int(input("Enter Second Number"))
print("Before Swapping")
print("First Number:"+str(a))
print("Second Number:"+str(b))
temp=a
a=b
b=temp
print("After Swapping")
print("First Number:"+str(a))
print("Second Number:"+str(b))

num=int(input("Enter a number:"))
if (num%2==0):
    print("Number is even")
else:
    print("Number is odd")

l=str(input("Enter alphabet:"))
if (l=='a' or l=='e'or l== 'i' or l=='o' or l=='u'):
  print(l+" is vowel")
else:
  print(l+" is consonent")

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=int(input("Enter third number:"))
if (a>b and a>c):
  print("greater is "+str(a))
elif (b>a and b>c):
  print("greater is "+str(b))
else:
  print("greater is "+(str(c)))

yr=int(input("Enter year:"))
if (yr%4==0):
  if (yr%100):
    if (yr%400):
      print("Leap year")
    else:
      print("not leap year")
  else:
    print("leap year")
else:
  print("not leap year")

num=int(input("Enter number:"))
if (num>0):
  print("Number is postive")
elif (num==0):
  print("Number neither positive or negative it is zero")
else:
  print("Number is negative")

limit=int(input("limit of numbers:"))
sum=0
for i in range(1,limit+1):
  sum=sum+i
print("Sum:"+str(sum))

num=int(input("Enter number:"))
fact=1
for i in range(1,num+1):
  fact=fact*i
print("Factorial of "+str(num)+"=" +str(fact))

num=int(input("Enter number:"))
limit=int(input("Enter limit"))
print("Multiplication table")
for i in range(1,limit+1):
  mul=i*num
  print(str(i)+"x"+str(num)+"="+str(mul))

num=int(input("Enter limit:"))
first=0
second=1
print("\nFibonacci series:")
print(first)
print(second)
for i in range(2, num):
  next=first+second
  print(next)
  first=second 
  second=next

a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
if(a>b):
    max=a
else:
    max=b
while(1):
    if(max%a==0 and max%b==0):
        print("LCM is:",max)
        break
    max=max+1

num=int(input("Enter Number"))
count=0
while(num!=0):
  num=num//10
  count=count+1
print("Number of digits:%d"%count)

num=int(input("Enter number:"))
rev=0
while (num>0):
  rem=num%10
  rev=(rev*10)+rem
  num=num//10
print("Reverse of entered number:%d"%rev)

num=int(input("Enter Number:"))
pow=int(input("Enter power:"))
power=1
for i in range(1,pow+1):
  power=power*num
print("power of number:",power)

num=int(input("Enter Number:"))
reserve=num
reverse=0
while (num>0):
  remainder=num%10
  reverse=(reverse*10)+remainder
  num=num//10
if (reserve==reverse):
  print("Number is palindrome")
else:
  print("Number is not palindrome")

