# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mANzaaYwmuVxSEXMoK8DkjKN3Dumz4Pi
"""

print("Hello, World!")

num= int(input("Enter a number:"))
print("Enterd number is: "+str(num))

n1=int(input("Enter first number:"))
n2=int(input("Enter second number:"))
sum=n1+n2
print("sum:"+str(sum))

f=float(input("first number:"))
s=float(input("second number:"))
mul=s*f
print("Result:"+str(mul))

n1=int(input("Divident:"))
n2=int(input("Divisor:"))
q=n1//n2
r=n1%n2
print("Quotient:"+str(q))
print("Remainder:"+str(r))

a=int(input("Enter First Number:"))
b=int(input("Enter Second Number"))
print("Before Swapping")
print("First Number:"+str(a))
print("Second Number:"+str(b))
temp=a
a=b
b=temp
print("After Swapping")
print("First Number:"+str(a))
print("Second Number:"+str(b))

num=int(input("Enter a number:"))
if (num%2==0):
    print("Number is even")
else:
    print("Number is odd")

l=str(input("Enter alphabet:"))
if (l=='a' or l=='e'or l== 'i' or l=='o' or l=='u'):
  print(l+" is vowel")
else:
  print(l+" is consonent")

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=int(input("Enter third number:"))
if (a>b and a>c):
  print("greater is "+str(a))
elif (b>a and b>c):
  print("greater is "+str(b))
else:
  print("greater is "+(str(c)))

yr=int(input("Enter year:"))
if (yr%4==0):
  if (yr%100):
    if (yr%400):
      print("Leap year")
    else:
      print("not leap year")
  else:
    print("leap year")
else:
  print("not leap year")

num=int(input("Enter number:"))
if (num>0):
  print("Number is postive")
elif (num==0):
  print("Number neither positive or negative it is zero")
else:
  print("Number is negative")

limit=int(input("limit of numbers:"))
sum=0
for i in range(1,limit+1):
  sum=sum+i
print("Sum:"+str(sum))

num=int(input("Enter number:"))
fact=1
for i in range(1,num+1):
  fact=fact*i
print("Factorial of "+str(num)+"=" +str(fact))

